# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
# file = "src/schema.rs"
file = "C:\\Projects\\rust\\rust-blog\\domain\\src\\schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\Projects\\rust\\rust-blog\\infrastructure\\migrations"
